### ISSUE TITLE
Occasional crash

### ISSUE THREAD

**Issue by zephray** [ntzyz/new-blog#6]
Occasionally happens. 

```
Aug 08 03:57:28 ntzyz-bwg node[2977]: Unhandled Rejection at: Promise Promise {
Aug 08 03:57:28 ntzyz-bwg node[2977]:   <rejected> TypeError: Cannot read property 'status' of undefined
Aug 08 03:57:28 ntzyz-bwg node[2977]:     at server-bundle.js:1:83396
Aug 08 03:57:28 ntzyz-bwg node[2977]:     at <anonymous>
Aug 08 03:57:28 ntzyz-bwg node[2977]:     at process._tickCallback (internal/process/next_tick.js:188:7) } reason: TypeError: Cannot read property 'status' of undefined
Aug 08 03:57:28 ntzyz-bwg node[2977]:     at server-bundle.js:1:83396
Aug 08 03:57:28 ntzyz-bwg node[2977]:     at <anonymous>
Aug 08 03:57:28 ntzyz-bwg node[2977]:     at process._tickCallback (internal/process/next_tick.js:188:7)
Aug 08 03:57:28 ntzyz-bwg systemd[1]: zpr-blog-i.service: Main process exited, code=exited, status=1/FAILURE
Aug 08 03:57:28 ntzyz-bwg systemd[1]: zpr-blog-i.service: Failed with result 'exit-code'.
```

**Comment by ntzyz** [comment]
It seems to be a DNS issue, `GETADDRINFO(3)` occasionally returns `EAI_SYSTEM` and `errno` is `ENOTFOUND`. Write your hostname to hosts can fix this problem.

On my own instance I never saw such error, so I'm wondering if it is GoDaddy's bug?

**Comment by zephray** [comment]
Applied proposed solution. The problem seems to be solved.
